download:
  description: "Сваля видео или плейлист от даден URL."
  fields:
    url:
      description: "URL на видеото или плейлиста."
      example: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    format:
      description: "Желан формат (mp3 или mp4)."
      example: "mp3"
    playlist_items:
      description: "При подаден плейлист - сваля всички видеа (`all`) или само първото (`first`)."
      example: "all"

cancel:
  description: "Незабавно прекратява текущото сваляне."